name: AWS ECR Deploy
on:
  push:
    branches:
      - lambda

jobs:
  build-ui-image:
    name: Build and deploy image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./UI

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # Log into dockerhub
      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: emmanuelu17
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # See  https://buildpacks.io/docs/buildpack-author-guide/publishing-with-github-actions/
      - name: Setup-tools
        uses: buildpacks/github-actions/setup-tools@v5.1.0

      - name: Setup pack
        uses: buildpacks/github-actions/setup-pack@v5.1.0

      # See more on paketo web servers https://github.com/paketo-buildpacks/web-servers
      # See for more on nginx config https://docs.vmware.com/en/VMware-Tanzu-Buildpacks/services/tanzu-buildpacks/GUID-nginx-nginx-buildpack.html
      - name: Build image
        run: |
          #!/usr/bin/env bash
          pack config default-builder paketobuildpacks/builder:base
          pack build emmanuelu17/websocket-ui --buildpack paketo-buildpacks/web-servers \
          --env "BP_WEB_SERVER=nginx" \
          --env "BP_WEB_SERVER_ROOT=dist/websocket-ui" \
          --env "BP_WEB_SERVER_ENABLE_PUSH_STATE=true" \
          --env "NODE_ENV=production"
        shell: bash

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Tag & Publish to Docker Hub
        run: |
          #!/usr/bin/env bash
          docker push --all-tags emmanuelu17/websocket-ui
        shell: bash

  build-native-image:
    name: Build and Deploy native image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'

      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: emmanuelu17
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build native image
        run: mvn -Pnative spring-boot:build-image -DskipTests

      - name: Set up docker build
        uses: docker/setup-buildx-action@v3

      - name: Push native image to dockerhub
        run: |
          docker image tag emmanuelu17/server-side-event:latest emmanuelu17/sse:latest
          docker push --all-tags emmanuelu17/sse